import turtle
from config import *

class Letters:
    def __init__(self, t:turtle.Turtle) -> None:
        self.letter_turtle = t 
        self.letter_turtle.pu()

        
    def start(self):
        self.startx= -400
        self.letter_turtle.setx(self.startx)
        self.letter_turtle.sety(200)
        self.letter_turtle.width(10)
        self.letter_turtle.speed(0)
        
    def print_text(self, text:str, c:str):
        txt = text.upper()
        self.start()
        for i in txt:
            if self.letter_turtle.xcor() > WINDOW_WIDTH // 2:
                self.printNewLine()
            if i == 'A':
                self.printA(c)
            elif i == 'B':
                self.printB(c)
            elif i == 'C':
                self.printC(c)
            elif i == 'D':
                self.printD(c)
            elif i == 'E':
                self.printE(c)
            elif i == 'F':
                self.printF(c)
            elif i == 'G':
                self.printG(c)
            elif i == 'H':
                self.printH(c)
            elif i == 'I':
                self.printI(c)
            elif i == 'J':
                self.printJ(c)
            elif i == 'K':
                self.printK(c)
            elif i == 'L':
                self.printL(c)
            elif i == 'M':
                self.printM(c)
            elif i == 'N':
                self.printN(c)
            elif i == 'O':
                self.printO(c)
            elif i == 'P':
                self.printP(c)
            elif i == 'Q':
                self.printQ(c)
            elif i == 'R':
                self.printR(c)
            elif i == 'S':
                self.printS(c)
            elif i == 'T':
                self.printT(c)
            elif i == 'U':
                self.printU(c)
            elif i == 'V':
                self.printV(c)
            elif i == 'W':
                self.printW(c)
            elif i == 'X':
                self.printX(c)
            elif i == 'Y':
                self.printY(c)
            elif i == 'Z':
                self.printZ(c)
            elif i == ' ':
                self.printBlank()
            elif i == '/':
                self.printNewLine()
            elif i == '1':
                self.letter_turtle.write(" 1 ", font=("Arial", 76))
                self.printBlank()
            elif i == '2':
                self.letter_turtle.write(" 2 ", font=("Arial", 76))
                self.printBlank()
            elif i == '3':
                self.letter_turtle.write(" 3 ", font=("Arial", 76))
                self.printBlank()
            elif i == '4':
                self.letter_turtle.write(" 4 ", font=("Arial", 76))
                self.printBlank()
            elif i == '5':
                self.letter_turtle.write(" 5 ", font=("Arial", 76))
                self.printBlank()
            elif i == '6':
                self.letter_turtle.write(" 6 ", font=("Arial", 76))
                self.printBlank()
            elif i == '7':
                self.letter_turtle.write(" 7 ", font=("Arial", 76))
                self.printBlank()
            elif i == '8':
                self.letter_turtle.write(" 8 ", font=("Arial", 76))
                self.printBlank()
            elif i == '9':
                self.letter_turtle.write(" 9 ", font=("Arial", 76))
                self.printBlank()
            elif i == '0':
                self.letter_turtle.write(" 0 ", font=("Arial", 76))
                self.printBlank()
            self.printBlank()
            
            
    def printNewLine(self):
        self.letter_turtle.penup()
        self.letter_turtle.setx(self.startx-10)
        self.letter_turtle.sety(self.letter_turtle.ycor()-120)
        self.letter_turtle.width(4)
       
        
    def printBlank(self):
        self.letter_turtle.penup()
        self.letter_turtle.forward(30)
       

    def printA(self, color):
        self.letter_turtle.pendown()
        self.letter_turtle.color(color)
        self.letter_turtle.left(90)
        self.letter_turtle.forward(100)
        self.letter_turtle.right(90)
        self.letter_turtle.forward(50)
        self.letter_turtle.right(90)
        self.letter_turtle.forward(50)
        self.letter_turtle.right(90)
        self.letter_turtle.forward(50)
        self.letter_turtle.left(180)
        self.letter_turtle.forward(50)
        self.letter_turtle.right(90)
        self.letter_turtle.forward(50)
        self.letter_turtle.left(90)


    def printB(self, color):
        self.letter_turtle.pendown()
        self.letter_turtle.color(color)
        self.letter_turtle.left(90)
        self.letter_turtle.forward(100)
        self.letter_turtle.right(90)
        self.letter_turtle.forward(50)
        self.letter_turtle.right(90)
        self.letter_turtle.forward(50)
        self.letter_turtle.right(90)
        self.letter_turtle.forward(50)
        self.letter_turtle.right(180)
        self.letter_turtle.forward(50)
        self.letter_turtle.right(90)
        self.letter_turtle.forward(50)
        self.letter_turtle.right(90)
        self.letter_turtle.forward(50)
        self.letter_turtle.left(180)
        self.letter_turtle.forward(50)

    def printC(self, color):
        self.letter_turtle.pendown()
        self.letter_turtle.color(color)
        self.letter_turtle.forward(50)
        self.letter_turtle.left(180)
        self.letter_turtle.forward(50)
        self.letter_turtle.right(90)
        self.letter_turtle.forward(100)
        self.letter_turtle.right(90)
        self.letter_turtle.forward(50)
        self.letter_turtle.right(90)
        self.letter_turtle.penup()
        self.letter_turtle.forward(100)
        self.letter_turtle.left(90)
        self.letter_turtle.pendown()

    def printD(self, color):
        self.letter_turtle.pendown()
        self.letter_turtle.color(color)
        self.letter_turtle.forward(50)
        self.letter_turtle.left(180)
        self.letter_turtle.forward(50)
        self.letter_turtle.right(90)
        self.letter_turtle.forward(100)
        self.letter_turtle.right(90)
        self.letter_turtle.forward(50)
        self.letter_turtle.right(90)
        self.letter_turtle.forward(100)
        self.letter_turtle.left(90)


    def printE(self, color):
        self.letter_turtle.pendown()
        self.letter_turtle.color(color)
        self.letter_turtle.forward(50)
        self.letter_turtle.left(180)
        self.letter_turtle.forward(50)
        self.letter_turtle.right(90)
        self.letter_turtle.forward(50)
        self.letter_turtle.right(90)
        self.letter_turtle.forward(50)
        self.letter_turtle.right(180)
        self.letter_turtle.forward(50)
        self.letter_turtle.right(90)
        self.letter_turtle.forward(50)
        self.letter_turtle.right(90)
        self.letter_turtle.forward(50)
        self.letter_turtle.right(90)
        self.letter_turtle.penup()
        self.letter_turtle.forward(100)
        self.letter_turtle.left(90)
        self.letter_turtle.pendown()

    def printF(self, color):
        self.letter_turtle.pendown()
        self.letter_turtle.color(color)
        self.letter_turtle.left(90)
        self.letter_turtle.forward(50)
        self.letter_turtle.right(90)
        self.letter_turtle.forward(50)
        self.letter_turtle.right(180)
        self.letter_turtle.forward(50)
        self.letter_turtle.right(90)
        self.letter_turtle.forward(50)
        self.letter_turtle.right(90)
        self.letter_turtle.forward(50)
        self.letter_turtle.right(90)
        self.letter_turtle.penup()
        self.letter_turtle.forward(100)
        self.letter_turtle.left(90)
        self.letter_turtle.pendown()


    def printG(self, color):
        self.letter_turtle.pendown()
        self.letter_turtle.color(color)
        self.letter_turtle.forward(50)
        self.letter_turtle.left(180)
        self.letter_turtle.forward(50)
        self.letter_turtle.right(90)
        self.letter_turtle.forward(100)
        self.letter_turtle.right(90)
        self.letter_turtle.forward(50)
        self.letter_turtle.right(90)
        self.letter_turtle.penup()
        self.letter_turtle.forward(50)
        self.letter_turtle.pendown()
        self.letter_turtle.forward(50)
        self.letter_turtle.back(50)
        self.letter_turtle.right(90)
        self.letter_turtle.forward(20)
        self.letter_turtle.back(20)
        self.letter_turtle.left(90)
        self.letter_turtle.forward(50)
        self.letter_turtle.left(90)
        

    def printH(self, color):
        self.letter_turtle.pendown()
        self.letter_turtle.color(color)
        self.letter_turtle.left(90)
        self.letter_turtle.forward(50)
        self.letter_turtle.right(90)
        self.letter_turtle.forward(50)
        self.letter_turtle.right(180)
        self.letter_turtle.forward(50)
        self.letter_turtle.right(90)
        self.letter_turtle.forward(50)
        self.letter_turtle.right(90)
        self.letter_turtle.penup()
        self.letter_turtle.forward(50)
        self.letter_turtle.right(90)
        self.letter_turtle.pendown()
        self.letter_turtle.forward(100)
        self.letter_turtle.left(90)


    def printI(self, color):
        self.letter_turtle.pendown()
        self.letter_turtle.color(color)
        self.letter_turtle.forward(50)
        self.letter_turtle.left(180)
        self.letter_turtle.forward(25)
        self.letter_turtle.right(90)
        self.letter_turtle.forward(100)
        self.letter_turtle.left(90)
        self.letter_turtle.forward(25)
        self.letter_turtle.left(180)
        self.letter_turtle.forward(50)
        self.letter_turtle.penup()
        self.letter_turtle.right(90)
        self.letter_turtle.forward(100)
        self.letter_turtle.left(90)
        self.letter_turtle.pendown()

    def printJ(self, color):
        self.letter_turtle.left(90)
        self.letter_turtle.forward(50)
        self.letter_turtle.left(180)
        self.letter_turtle.pendown()
        self.letter_turtle.color(color)
        self.letter_turtle.forward(50)
        self.letter_turtle.left(90)
        self.letter_turtle.forward(25)
        self.letter_turtle.left(90)
        self.letter_turtle.forward(100)
        self.letter_turtle.left(90)
        self.letter_turtle.forward(25)
        self.letter_turtle.left(180)
        self.letter_turtle.forward(50)
        self.letter_turtle.penup()
        self.letter_turtle.right(90)
        self.letter_turtle.forward(100)
        self.letter_turtle.left(90)
        self.letter_turtle.pendown()


    def printK(self, color):
        self.letter_turtle.pendown()
        self.letter_turtle.color(color)
        self.letter_turtle.left(90)
        self.letter_turtle.forward(100)
        self.letter_turtle.left(180)
        self.letter_turtle.forward(50)
        self.letter_turtle.left(135)
        self.letter_turtle.forward(70.71)
        self.letter_turtle.left(180)
        self.letter_turtle.forward(70.71)
        self.letter_turtle.left(90)
        self.letter_turtle.forward(70.71)
        self.letter_turtle.left(45)

    def printL(self, color):
        self.letter_turtle.left(90)
        self.letter_turtle.forward(100)
        self.letter_turtle.pendown()
        self.letter_turtle.color(color)
        self.letter_turtle.left(180)
        self.letter_turtle.forward(100)
        self.letter_turtle.left(90)
        self.letter_turtle.forward(50)


    def printM(self, color):
        self.letter_turtle.pendown()
        self.letter_turtle.color(color)
        self.letter_turtle.left(90)
        self.letter_turtle.forward(100)
        self.letter_turtle.right(135)
        self.letter_turtle.forward(55.90)
        self.letter_turtle.left(90)
        self.letter_turtle.forward(55.90)
        self.letter_turtle.right(135)
        self.letter_turtle.forward(100)
        self.letter_turtle.left(90)


    def printN(self, color):
        self.letter_turtle.pendown()
        self.letter_turtle.color(color)
        self.letter_turtle.left(90)
        self.letter_turtle.forward(100)
        self.letter_turtle.right(150)
        self.letter_turtle.forward(115.70)
        self.letter_turtle.left(150)
        self.letter_turtle.forward(100)
        self.letter_turtle.left(180)
        self.letter_turtle.forward(100)
        self.letter_turtle.left(90)

    def printO(self, color):
        self.letter_turtle.left(90)
        self.letter_turtle.forward(5)
        self.letter_turtle.pendown()
        self.letter_turtle.color(color)
        self.letter_turtle.forward(90)
        self.letter_turtle.right(45)
        self.letter_turtle.forward(7.07)
        self.letter_turtle.right(45)
        self.letter_turtle.forward(40)
        self.letter_turtle.right(45)
        self.letter_turtle.forward(7.07)
        self.letter_turtle.right(45)
        self.letter_turtle.forward(90)
        self.letter_turtle.right(45)
        self.letter_turtle.forward(7.07)
        self.letter_turtle.right(45)
        self.letter_turtle.forward(40)
        self.letter_turtle.right(45)
        self.letter_turtle.forward(7.07)
        self.letter_turtle.right(180)
        self.letter_turtle.forward(7.07)
        self.letter_turtle.left(45)
        self.letter_turtle.forward(40)
        self.letter_turtle.penup()
        self.letter_turtle.forward(5)
        self.letter_turtle.pendown()

    def printP(self, color):
        self.letter_turtle.pendown()
        self.letter_turtle.color(color)
        self.letter_turtle.left(90)
        self.letter_turtle.forward(100)
        self.letter_turtle.right(90)
        self.letter_turtle.forward(45)
        self.letter_turtle.right(45)
        self.letter_turtle.forward(7.07)
        self.letter_turtle.right(45)
        self.letter_turtle.forward(40)
        self.letter_turtle.right(45)
        self.letter_turtle.forward(7.07)
        self.letter_turtle.right(45)
        self.letter_turtle.forward(45)
        self.letter_turtle.left(90)
        self.letter_turtle.forward(50)
        self.letter_turtle.left(90)
        self.letter_turtle.penup()
        self.letter_turtle.forward(50)
        self.letter_turtle.pendown()

    def printQ(self, color):
        self.letter_turtle.left(90)
        self.letter_turtle.forward(10)
        self.letter_turtle.pendown()
        self.letter_turtle.color(color)
        self.letter_turtle.forward(80)
        self.letter_turtle.right(45)
        self.letter_turtle.forward(14.14)
        self.letter_turtle.right(45)
        self.letter_turtle.forward(30)
        self.letter_turtle.right(45)
        self.letter_turtle.forward(14.14)
        self.letter_turtle.right(45)
        self.letter_turtle.forward(80)
        self.letter_turtle.right(45)
        self.letter_turtle.forward(14.14)
        self.letter_turtle.right(45)
        self.letter_turtle.forward(30)
        self.letter_turtle.right(45)
        self.letter_turtle.forward(14.14)
        self.letter_turtle.right(180)
        self.letter_turtle.forward(14.14)
        self.letter_turtle.left(45)
        self.letter_turtle.forward(30)
        self.letter_turtle.left(45)
        self.letter_turtle.forward(7.07)
        self.letter_turtle.left(90)
        self.letter_turtle.forward(7.07)
        self.letter_turtle.left(180)
        self.letter_turtle.forward(14.14)
        self.letter_turtle.left(180)
        self.letter_turtle.forward(7.07)
        self.letter_turtle.left(90)
        self.letter_turtle.forward(7.07)
        self.letter_turtle.left(135)
        self.letter_turtle.penup()
        self.letter_turtle.forward(5)
        self.letter_turtle.pendown()

    def printR(self, color):
        self.letter_turtle.pendown()
        self.letter_turtle.color(color)
        self.letter_turtle.left(90)
        self.letter_turtle.forward(100)
        self.letter_turtle.right(90)
        self.letter_turtle.forward(45)
        self.letter_turtle.right(45)
        self.letter_turtle.forward(7.07)
        self.letter_turtle.right(45)
        self.letter_turtle.forward(40)
        self.letter_turtle.right(45)
        self.letter_turtle.forward(7.07)
        self.letter_turtle.right(45)
        self.letter_turtle.forward(45)
        self.letter_turtle.left(180)
        self.letter_turtle.forward(20)
        self.letter_turtle.right(60)
        self.letter_turtle.forward(58.30)
        self.letter_turtle.left(60)

    def printS(self, color):
        self.letter_turtle.pendown()
        self.letter_turtle.color(color)
        self.letter_turtle.forward(45)
        self.letter_turtle.left(45)
        self.letter_turtle.forward(7.07)
        self.letter_turtle.left(45)
        self.letter_turtle.forward(40)
        self.letter_turtle.left(45)
        self.letter_turtle.forward(7.07)
        self.letter_turtle.left(45)
        self.letter_turtle.forward(40)
        self.letter_turtle.right(45)
        self.letter_turtle.forward(7.07)
        self.letter_turtle.right(45)
        self.letter_turtle.forward(40)
        self.letter_turtle.right(45)
        self.letter_turtle.forward(7.07)
        self.letter_turtle.right(45)
        self.letter_turtle.forward(45)
        self.letter_turtle.penup()
        self.letter_turtle.forward(5)
        self.letter_turtle.right(90)
        self.letter_turtle.forward(100)
        self.letter_turtle.right(90)
        self.letter_turtle.forward(5)
        self.letter_turtle.left(180)
        self.letter_turtle.pendown()

    def printT(self, color):
        self.letter_turtle.penup()
        self.letter_turtle.forward(30)
        self.letter_turtle.left(90)
        self.letter_turtle.pendown()
        self.letter_turtle.color(color)
        self.letter_turtle.forward(100)
        self.letter_turtle.left(90)
        self.letter_turtle.forward(30)
        self.letter_turtle.left(180)
        self.letter_turtle.forward(60)
        self.letter_turtle.penup()
        self.letter_turtle.right(90)
        self.letter_turtle.forward(100)
        self.letter_turtle.left(90)
        self.letter_turtle.pendown()

    def printU(self, color):
        self.letter_turtle.forward(5)
        self.letter_turtle.pendown()
        self.letter_turtle.color(color)
        self.letter_turtle.left(135)
        self.letter_turtle.forward(7.07)
        self.letter_turtle.right(45)
        self.letter_turtle.forward(95)
        self.letter_turtle.left(180)
        self.letter_turtle.forward(95)
        self.letter_turtle.left(45)
        self.letter_turtle.forward(7.07)
        self.letter_turtle.left(45)
        self.letter_turtle.forward(40)
        self.letter_turtle.left(45)
        self.letter_turtle.forward(7.07)
        self.letter_turtle.left(45)
        self.letter_turtle.forward(95)
        self.letter_turtle.left(180)
        self.letter_turtle.forward(95)
        self.letter_turtle.right(45)
        self.letter_turtle.forward(7.07)
        self.letter_turtle.left(135)
        self.letter_turtle.penup()
        self.letter_turtle.forward(5)
        self.letter_turtle.pendown()

    def printV(self, color):
        self.letter_turtle.forward(25)
        self.letter_turtle.pendown()
        self.letter_turtle.color(color)
        self.letter_turtle.left(135)
        self.letter_turtle.forward(55.90)
        self.letter_turtle.right(45)
        self.letter_turtle.forward(50)
        self.letter_turtle.left(180)
        self.letter_turtle.forward(50)
        self.letter_turtle.left(45)
        self.letter_turtle.forward(55.90)
        self.letter_turtle.left(90)
        self.letter_turtle.forward(55.90)
        self.letter_turtle.left(45)
        self.letter_turtle.forward(50)
        self.letter_turtle.left(180)
        self.letter_turtle.forward(50)
        self.letter_turtle.penup()
        self.letter_turtle.forward(50)
        self.letter_turtle.left(90)
        self.letter_turtle.pendown()

    def printW(self, color):
        self.letter_turtle.pendown()
        self.letter_turtle.color(color)
        self.letter_turtle.left(90)
        self.letter_turtle.forward(100)
        self.letter_turtle.left(180)
        self.letter_turtle.forward(100)
        self.letter_turtle.left(135)
        self.letter_turtle.forward(55.90)
        self.letter_turtle.right(90)
        self.letter_turtle.forward(55.90)
        self.letter_turtle.left(135)
        self.letter_turtle.forward(100)
        self.letter_turtle.left(180)
        self.letter_turtle.forward(100)
        self.letter_turtle.left(90)

    def printX(self, color):
        self.letter_turtle.forward(50)
        self.letter_turtle.pendown()
        self.letter_turtle.color(color)
        self.letter_turtle.left(116.551)
        self.letter_turtle.forward(111.80)
        self.letter_turtle.left(180)
        self.letter_turtle.forward(55.90)
        self.letter_turtle.right(53.102)
        self.letter_turtle.forward(55.90)
        self.letter_turtle.left(180)
        self.letter_turtle.forward(111.80)
        self.letter_turtle.right(153.449)
        self.letter_turtle.penup()
        self.letter_turtle.forward(100)
        self.letter_turtle.left(90)
        self.letter_turtle.pendown()

    def printY(self, color):
        self.letter_turtle.forward(25)
        self.letter_turtle.pendown()
        self.letter_turtle.color(color)
        self.letter_turtle.left(90)
        self.letter_turtle.forward(50)
        self.letter_turtle.left(40)
        self.letter_turtle.forward(65)
        self.letter_turtle.left(180)
        self.letter_turtle.forward(65)
        self.letter_turtle.left(100)
        self.letter_turtle.forward(65)
        self.letter_turtle.left(180)
        self.letter_turtle.forward(65)
        self.letter_turtle.left(40)
        self.letter_turtle.forward(50)
        self.letter_turtle.left(90)
        self.letter_turtle.penup()
        self.letter_turtle.forward(30)
        self.letter_turtle.pendown()

    def printZ(self, color):
        self.letter_turtle.pendown()
        self.letter_turtle.color(color)
        self.letter_turtle.left(63.45)
        self.letter_turtle.forward(111.80)
        self.letter_turtle.left(116.55)
        self.letter_turtle.forward(50)
        self.letter_turtle.left(180)
        self.letter_turtle.forward(50)
        self.letter_turtle.right(116.551)
        self.letter_turtle.forward(111.80)
        self.letter_turtle.left(116.55)
        self.letter_turtle.forward(50)